// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-2019 Datadog, Inc.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/DataDog/watermarkpodautoscaler/pkg/apis/datadoghq/v1alpha1"
	scheme "github.com/DataDog/watermarkpodautoscaler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WatermarkPodAutoscalersGetter has a method to return a WatermarkPodAutoscalerInterface.
// A group's client should implement this interface.
type WatermarkPodAutoscalersGetter interface {
	WatermarkPodAutoscalers(namespace string) WatermarkPodAutoscalerInterface
}

// WatermarkPodAutoscalerInterface has methods to work with WatermarkPodAutoscaler resources.
type WatermarkPodAutoscalerInterface interface {
	Create(*v1alpha1.WatermarkPodAutoscaler) (*v1alpha1.WatermarkPodAutoscaler, error)
	Update(*v1alpha1.WatermarkPodAutoscaler) (*v1alpha1.WatermarkPodAutoscaler, error)
	UpdateStatus(*v1alpha1.WatermarkPodAutoscaler) (*v1alpha1.WatermarkPodAutoscaler, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.WatermarkPodAutoscaler, error)
	List(opts v1.ListOptions) (*v1alpha1.WatermarkPodAutoscalerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WatermarkPodAutoscaler, err error)
	WatermarkPodAutoscalerExpansion
}

// watermarkPodAutoscalers implements WatermarkPodAutoscalerInterface
type watermarkPodAutoscalers struct {
	client rest.Interface
	ns     string
}

// newWatermarkPodAutoscalers returns a WatermarkPodAutoscalers
func newWatermarkPodAutoscalers(c *DatadoghqV1alpha1Client, namespace string) *watermarkPodAutoscalers {
	return &watermarkPodAutoscalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the watermarkPodAutoscaler, and returns the corresponding watermarkPodAutoscaler object, and an error if there is any.
func (c *watermarkPodAutoscalers) Get(name string, options v1.GetOptions) (result *v1alpha1.WatermarkPodAutoscaler, err error) {
	result = &v1alpha1.WatermarkPodAutoscaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WatermarkPodAutoscalers that match those selectors.
func (c *watermarkPodAutoscalers) List(opts v1.ListOptions) (result *v1alpha1.WatermarkPodAutoscalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WatermarkPodAutoscalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested watermarkPodAutoscalers.
func (c *watermarkPodAutoscalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a watermarkPodAutoscaler and creates it.  Returns the server's representation of the watermarkPodAutoscaler, and an error, if there is any.
func (c *watermarkPodAutoscalers) Create(watermarkPodAutoscaler *v1alpha1.WatermarkPodAutoscaler) (result *v1alpha1.WatermarkPodAutoscaler, err error) {
	result = &v1alpha1.WatermarkPodAutoscaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		Body(watermarkPodAutoscaler).
		Do().
		Into(result)
	return
}

// Update takes the representation of a watermarkPodAutoscaler and updates it. Returns the server's representation of the watermarkPodAutoscaler, and an error, if there is any.
func (c *watermarkPodAutoscalers) Update(watermarkPodAutoscaler *v1alpha1.WatermarkPodAutoscaler) (result *v1alpha1.WatermarkPodAutoscaler, err error) {
	result = &v1alpha1.WatermarkPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		Name(watermarkPodAutoscaler.Name).
		Body(watermarkPodAutoscaler).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *watermarkPodAutoscalers) UpdateStatus(watermarkPodAutoscaler *v1alpha1.WatermarkPodAutoscaler) (result *v1alpha1.WatermarkPodAutoscaler, err error) {
	result = &v1alpha1.WatermarkPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		Name(watermarkPodAutoscaler.Name).
		SubResource("status").
		Body(watermarkPodAutoscaler).
		Do().
		Into(result)
	return
}

// Delete takes name of the watermarkPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *watermarkPodAutoscalers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *watermarkPodAutoscalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched watermarkPodAutoscaler.
func (c *watermarkPodAutoscalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WatermarkPodAutoscaler, err error) {
	result = &v1alpha1.WatermarkPodAutoscaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("watermarkpodautoscalers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
