image: golang:1.14
variables:
  GO111MODULE: "on"
  PROJECTNAME: "watermarkpodautoscaler"
  TARGET_TAG: v$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
  DOCKER_REGISTRY: "486234852809.dkr.ecr.us-east-1.amazonaws.com/ci"
  GOPATH: "$CI_PROJECT_DIR/.cache"
  FAKE_EXTERNALSERVER_DOCKER_IMAGE: docker.io/cedriclamoriniere/fake-custom-metrics-server:latest
cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .cache
  policy: pull-push

stages:
  - build
  - test
  - image
  - test-e2e
  - release

before_script:
  - mkdir -p .cache
  - make install-tools

build:
  stage: build
  tags: [ "runner:main", "size:large" ]
  script:
  - make build

unit_tests:
  stage: test
  tags: [ "runner:main", "size:large" ]
  script:
  - make test

generate_code:
  stage: test
  tags: [ "runner:main", "size:large" ]
  script:
    - make generate manifests
    - git diff --exit-code

lint_code:
  stage: test
  tags: [ "runner:main", "size:large" ]
  script:
  - make lint

build_image:
  stage: image
  tags: [ "runner:docker", "size:large" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker-notary:0.6.1
  inherit:
    default: false
  script:
    - IMG=$DOCKER_REGISTRY/$PROJECTNAME:$TARGET_TAG make docker-build-ci docker-push

push_release_tag:
  only:
    - tags
  stage: release
  before_script: []
  tags: [ "runner:docker", "size:large" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker-notary:0.6.1
  script:
    - IMAGE_NAME=$DOCKER_REGISTRY/$PROJECTNAME:$TARGET_TAG
    - RELEASE_IMAGE_NAME=$DOCKER_REGISTRY/$PROJECTNAME:$CI_COMMIT_TAG
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $RELEASE_IMAGE_NAME
    - docker push $RELEASE_IMAGE_NAME
