[run]
  deadline = "5m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

[linters]
  enable-all = true
  disable = [
    "exhaustruct",
    "nonamedreturns",
    "revive",
    "lll",
    "dupl",
    "gocyclo",
    "gochecknoinits",
    "gochecknoglobals",
    "funlen",
    "gocognit",
    "cyclop",
    "gomnd",
    "wrapcheck",
    "forcetypeassert",
    "testpackage",
    "wastedassign",
    "thelper",
    "paralleltest",
    "nestif",
    "exhaustive",
    "err113",
    "gosec",
    "gci",
    "wsl",
    "godox",
    "godot",
    "nlreturn",
    "varnamelen",
    "tagliatelle",
    "containedctx",
    "contextcheck",
    "nilnil",
    "ireturn",
    "maintidx",
    "gocritic",
    "errchkjson",
    "gofumpt",
    "gomoddirectives",
    "prealloc",
    "rowserrcheck",
    "sqlclosecheck",
    "depguard",
    "perfsprint",
    "mnd",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = []

  # Exclude the following lint error:
  # /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/manager/manager.go:54:2:
  # Start redeclared (typecheck)
  [[issues.exclude-rules]]
    linters = ["typecheck"]
    text = "Start redeclared"

  # Exclude the following lint error:
  # /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/manager/manager.go:87:2:
  # other declaration of Start (typecheck)
  [[issues.exclude-rules]]
    linters = ["typecheck"]
    text = "other declaration of Start"
