# goreleaser is used only to generate the GitHub release.
# The generation of the docker image and its push to Docker Hub is done by GitLab.
builds: []
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
