resources:
- manager.yaml
images:
- name: controller
  newName: gcr.io/datadoghq/watermarkpodautoscaler
  newTag: v0.6.0-rc.1
- name: gcr.io/datadoghq/watermarkpodautoscaler
  newName: gcr.io/datadoghq/watermarkpodautoscaler
  newTag: v0.5.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
