resources:
- manager.yaml
images:
- name: gcr.io/datadoghq/watermarkpodautoscaler
  newName: gcr.io/datadoghq/watermarkpodautoscaler
  newTag: 0.3.0-rc.6
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
