// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-2020 Datadog, Inc.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// WatermarkPodAutoscalerListerExpansion allows custom methods to be added to
// WatermarkPodAutoscalerLister.
type WatermarkPodAutoscalerListerExpansion interface{}

// WatermarkPodAutoscalerNamespaceListerExpansion allows custom methods to be added to
// WatermarkPodAutoscalerNamespaceLister.
type WatermarkPodAutoscalerNamespaceListerExpansion interface{}
