
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: watermarkpodautoscaler-controller-manager
  name: watermarkpodautoscaler-controller-manager-metrics-monitor
  namespace: datadog
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      control-plane: watermarkpodautoscaler-controller-manager
