apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-metrics-reader
rules:
  - apiGroups:
      - external.metrics.k8s.io
      - metrics.k8s.io
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-metrics-reader
subjects:
  - kind: ServiceAccount
    name: watermarkpodautoscaler-controller-manager
    namespace: datadog
