apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: watermarkpodautoscaler-controller-manager
  name: watermarkpodautoscaler-controller-manager-metrics-service
  namespace: datadog
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: watermarkpodautoscaler-controller-manager
