# permissions for end users to edit watermarkpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watermarkpodautoscaler-editor-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - watermarkpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - watermarkpodautoscalers/status
  verbs:
  - get
