apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: watermarkpodautoscaler.datadoghq.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.currentMetrics[*].external.currentValue..
    name: value
    type: string
  - JSONPath: .spec.metrics[*].external.highWatermark..
    name: high watermark
    type: string
  - JSONPath: .spec.metrics[*].external.lowWatermark..
    name: low watermark
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  - JSONPath: .spec.minReplicas
    name: min replicas
    type: integer
  - JSONPath: .spec.maxReplicas
    name: max replicas
    type: integer
  group: datadoghq.com
  names:
    kind: WatermarkPodAutoscaler
    listKind: WatermarkPodAutoscalerList
    plural: watermarkpodautoscaler
    shortNames:
    - wpa
    singular: watermarkpodautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            algorithm:
              description: 'computed values take the # of replicas into account'
              type: string
            downscaleForbiddenWindowSeconds:
              description: 'part of HorizontalController, see comments in the k8s
                repo: pkg/controller/podautoscaler/horizontal.go'
              format: int32
              maximum: 600
              minimum: 1
              type: integer
            maxReplicas:
              format: int32
              maximum: 1000
              minimum: 1
              type: integer
            metrics:
              description: specifications that will be used to calculate the desired
                replica count
              items:
                properties:
                  external:
                    description: external refers to a global metric that is not associated
                      with any Kubernetes object. It allows autoscaling based on information
                      coming from components running outside of cluster (for example
                      length of queue in cloud messaging service, or QPS from loadbalancer
                      running outside of cluster).
                    properties:
                      highWatermark:
                        type: string
                      lowWatermark:
                        type: string
                      metricName:
                        description: metricName is the name of the metric in question.
                        type: string
                      metricSelector:
                        description: metricSelector is used to identify a specific
                          time series within a given metric.
                        type: object
                    required:
                    - metricName
                    type: object
                  type:
                    description: type is the type of metric source.  It should be
                      one of "Object", "Pods" or "Resource", each mapping to a matching
                      field in the object.
                    type: string
                required:
                - type
                type: object
              type: array
            minReplicas:
              format: int32
              maximum: 1000
              minimum: 1
              type: integer
            scaleTargetRef:
              description: 'part of HorizontalPodAutoscalerSpec, see comments in the
                k8s-1.10.8 repo: staging/src/k8s.io/api/autoscaling/v1/types.go reference
                to scaled resource; horizontal pod autoscaler will learn the current
                resource consumption and will set the desired number of pods by using
                its Scale subresource.'
              properties:
                apiVersion:
                  description: API version of the referent
                  type: string
                kind:
                  description: 'Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"'
                  type: string
                name:
                  description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                  type: string
              required:
              - kind
              - name
              type: object
            scaleUpLimitFactor:
              description: See the comment about this parameter above
              format: double
              maximum: 10
              minimum: 1
              type: number
            scaleUpLimitMinimum:
              description: See the comment about this parameter above
              format: int32
              maximum: 20
              minimum: 1
              type: integer
            tolerance:
              format: double
              maximum: 0.99
              minimum: 0.01
              type: number
            upscaleForbiddenWindowSeconds:
              format: int32
              maximum: 600
              minimum: 1
              type: integer
          required:
          - scaleTargetRef
          type: object
        status:
          properties:
            conditions:
              items:
                type: object
              type: array
            currentMetrics:
              items:
                type: object
              type: array
            currentReplicas:
              format: int32
              type: integer
            desiredReplicas:
              format: int32
              type: integer
            lastScaleTime:
              format: date-time
              type: string
            observedGeneration:
              format: int64
              type: integer
          required:
          - currentReplicas
          - desiredReplicas
          - currentMetrics
          - conditions
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
