apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: example-watermarkpodautoscaler
spec:
  # Add fields here
  maxReplicas: 3
  minReplicas: 1
  tolerance: 0.01
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: alpine
  metrics:
  - type: External
    external:
      highWatermark: "12000"
      lowWatermark: "8000"
      metricName: sinus
      metricSelector:
        matchLabels:
          foo: bar
