apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watermarkpodautoscaler
rules:
- apiGroups:
  - apps
  resources:
  - replicasets/scale
  - deployments/scale
  - statefulsets/scale
  verbs:
  - 'update'
  - 'get'
- apiGroups:
  - apps
  resourceNames:
  - watermarkpodautoscalers
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - datadoghq.com
  resources:
  - watermarkpodautoscalers
  - watermarkpodautoscalers/status
  verbs:
  - '*'
