apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watermarkpodautoscaler
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - watermarkpodautoscalers
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - datadoghq.com
  resources:
  - '*'
  verbs:
  - '*'
