kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watermarkpodautoscaler
subjects:
- kind: ServiceAccount
  name: watermarkpodautoscaler
  namespace: default
roleRef:
  kind: ClusterRole
  name: watermarkpodautoscaler
  apiGroup: rbac.authorization.k8s.io
