apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermarkPodAutoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: watermarkPodAutoscaler
  template:
    metadata:
      labels:
        name: watermarkPodAutoscaler
    spec:
      serviceAccountName: watermarkPodAutoscaler
      containers:
        - name: watermarkPodAutoscaler
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - watermarkPodAutoscaler
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "watermarkPodAutoscaler"
