kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watermarkpodautoscaler
subjects:
- kind: ServiceAccount
  name: watermarkpodautoscaler
roleRef:
  kind: Role
  name: watermarkpodautoscaler
  apiGroup: rbac.authorization.k8s.io
