apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: example-watermarkpodautoscaler
spec:
  # Add fields here
  maxReplicas: 3
  minReplicas: 1
  tolerance: 0.01
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: alpine
  readinessDelay: 10
  metrics:
    # Resource or External type supported
    # Example usage of External type
    - type: External
      external:
        highWatermark: "12000"
        lowWatermark: "8000"
        metricName: sinus
        metricSelector:
          matchLabels:
            foo: bar
  # Example usage of Resource type
  # - type: Resource
  #   resource:
  #     highWatermark: "50"
  #     lowWatermark: "10"
  #     name: cpu
  #     metricSelector:
  #       matchLabels:
  #         foo: bar
