{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "watermarkpodautoscaler.fullname" . }}-external-metrics-reader
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "watermarkpodautoscaler.fullname" . }}-external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "watermarkpodautoscaler.fullname" . }}-external-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
