{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  labels:
    {{- include "watermarkpodautoscaler.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
