{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  labels:
    {{- include "watermarkpodautoscaler.labels" . | nindent 4 }}
rules:
{{- if eq .Values.leaderElectionResourceLock "configmaps" }}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
    - watermarkpodautoscaler-lock
  verbs:
  - update
  - get
{{- end }}
{{- if eq .Values.leaderElectionResourceLock "leases" }}
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
    - watermarkpodautoscaler-lock
  verbs:
  - update
  - get
{{- end }}
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - 'create'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets/scale
  - deployments/scale
  - statefulsets/scale
  verbs:
  - 'update'
  - 'get'
- apiGroups:
  - apps
  resourceNames:
  - watermarkpodautoscalers
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - datadoghq.com
  resources:
  - watermarkpodautoscalers
  - watermarkpodautoscalers/status
  verbs:
  - '*'
{{- end -}}
