{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  labels:
    {{- include "watermarkpodautoscaler.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "watermarkpodautoscaler.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
