issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/watermarkpodautoscaler:pull_request

claim_pattern:
  event_name: pull_request_target
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/watermarkpodautoscaler/\.github/workflows/pr-backport\.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
