name: pull request linter
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ secrets.DD_GITHUB_TOKEN_GENERATOR_APP_ID }}
          private-key: ${{ secrets.DD_GITHUB_TOKEN_GENERATOR_PRIVATE_KEY }}
      - name: Verify Pull Request Labels
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          valid-labels: 'bug, enhancement, refactoring, documentation, tooling, dependencies'
          pull-request-number: '${{ github.event.pull_request.number }}'
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - if: github.event.pull_request.milestone == null && !contains(toJson(github.event.pull_request.labels.*.name), 'qa/skip-qa')
        run: echo "::error::Missing milestone or \`qa/skip-qa\` label" && exit 1
