name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow --tags
      -
        name: Get tag
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - 
        name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: ${{ github.repository_owner }}
            repo: watermarkpodautoscaler
            excludes: prerelease, draft
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --skip-publish
        env:
          COMMIT_TAG: ${{steps.tag.outputs.tag}}
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      -
        name: Generate Plugin manifest
        run: ./hack/plugin/generate-plugin-manifest.sh ${{steps.tag.outputs.tag}}
      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: dist/CHANGELOG.md
          prerelease: ${{ contains(github.ref, '-rc.') }}
          files: |
            dist/wpa-plugin.yaml
            dist/*.zip
            dist/*.tar.gz
        env:
          COMMIT_TAG: ${{steps.tag.outputs.tag}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # TODO: we need first to add the plugin manualy into the krew db repo.
      # -
      #  name: Update new plugin version in krew-index
      #  uses: rajatjindal/krew-release-bot@v0.0.40
      #  continue-on-error: true
      #  with:
      #    krew_template_file: dist/wpa-plugin.yaml
