apiVersion: v1
appVersion: v0.9.0
description: Watermark Pod Autoscaler
name: watermarkpodautoscaler
version: v0.5.1
dependencies:
  - name: datadog-crds
    version: "=1.3.0"
    alias: datadogCRDs
    repository: https://helm.datadoghq.com
    condition: lifecycleControl.enabled && datadogCRDs.crds.datadogMonitors
